### PR TITLE
Click cancel if a removal request has already been made - closes #5

### LINKED ISSUE #5: add a setting to automatically "cancel" if the URL is duplicated
Screen Shot 2020-01-20 at 11 25 15 AM

Can you make it automatically click on "cancel"?

Took a really quick look at the code, maybe something like:
```
    } else if ($dialog.text().includes("A removal request for this URL has already been made.")) {
      clickWithWait(["div[role='dialog'] button div:contains('Cancel')"]);
    }
```

You could make it more sophisticated and retry a couple times before cancelling with settings to configure it, but personally for me, I would just like to request the "cancel" feature.

### PR DESCRIPTION
**Pull request by DanielRuf**
It seems the UI loads the old or some general dialog before it shows the
final cancel dialog. This is not directly visible but can be seen when
we check the result of the `text()` method.

Adding the timeout in general solves this by waiting for the final /
latest dialog.
A better solution would be to wait until one of the final dialogs
appears and then we trigger a click event on the needed buttons.

The waitFor methods of puppeteer could be some helpful reference in this
case.

### CODE REVIEW

**Comment by DanielRuf** [comment]
> noitcudni force pushed changes to the base branch about 5 hours ago

To master? Ouch =(

**Comment by DanielRuf** [comment]
It seems you overwrote and removed my contribution / commit. Not that nice. Also the force-push on master.

Not sure why this was done. I will merge the changes in my fork and try to implement changes from the latest version and provide that for users since it seems you are not interested in contributions.

**Comment by noitcudni** [comment]
As I mention before, I was rewriting the whole project in Clojurescript. Hence, the force push. Sorry, I was trying to tell you that before, but it fell on deaf ears.

**Comment by DanielRuf** [comment]
> As I mention before, I was rewriting the whole project in Clojurescript. Hence, the force push. Sorry, I was trying to tell you that before, but it fell on deaf ears.

Normally you merge things / branches. This breaks / invalidates all forks and PRs ;-)
This is not how it should normally work as it produces headaches on many ends.

**Pull request closed without merging**
